apiVersion: v1
kind: ConfigMap
metadata:
  name: alonsocardenas-api-configmap
  namespace: alonsocardenas-api-ns
  labels:
    app: cardenasalonso-api

data:
  APP_ENV: "produccion"
  APP_PORT: "8085"
  APP_VERSION: "1.0.0"

