apiVersion: apps/v1
kind: Deployment
metadata:
  name: cardenasalonso-api-deployment
  namespace: cardenasalonso-api-ns
  labels:
    app: cardenasalonso-api

spec:
  replicas: 2
  selector:
    matchLabels:
      app: cardenasalonso-api
  template:
    metadata:
      labels:
        app: cardenasalonso-api
    spec:
      containers:
        - name: cardenasalonso-api
          image: cardenastrujilloalonso/cardenasalonso-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085
          env:
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  key: APP_ENV
                  name: cardenasalonso-api-configmap
            - name: APP_VERSION
              valueFrom:
                configMapKeyRef:
                  key: APP_VERSION
                  name: cardenasalonso-api-configmap
            - name: APP_PORT
              valueFrom:
                configMapKeyRef:
                  key: APP_PORT
                  name: cardenasalonso-api-configmap

            - name: SECRET_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: cardenasalonso-api-secret
            - name: SECRET_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: cardenasalonso-api-secret





